services:
    sio_test:
        user: app
        build:
            context: .
            args:
                USER_ID: ${USER_ID:-1000}
        ports:
            - "8337:8337"
        volumes:
            - .:/app:rw
        environment:
            - APP_ENV=dev

    postgres:
        image: postgres:15
        ports:
            - "15432:5432"
        container_name: 'postgresql'
        working_dir: /app
        restart: always
        environment:
            POSTGRES_DB: 'db'
            POSTGRES_USER: 'user'
            POSTGRES_PASSWORD: '123'
        volumes:
            - ./var/postgresql:/var/lib/postgresql/data
